#+title: Chapter Biology Feedback

* Notes
- Based on feedback/biology_methods_20230824_c2d06ba4_PS.pdf
- Categorisation system/War plan taken from [[cite:&heardScientistGuideWriting2016]], along with notes on which category means.
- Notation: XXpY/Z means page XX, paragraph Y, comment Z.  XXfY indicates figures.  Note to self: I should come up with a way for LaTeX to display line numbers.

* Category 1
Clear problems with straightforward solutions, e.g. grammar mistakes, reordering of sections, new title

- [X] 02p2: minor word corrections
- [X] 04p2: cite Charvin
- [X] 05p1: gene name for lipoamide dehydrogenase
- [X] 10p1: results -> data
- [X] 16p3: insert 'measurements of'
- [X] 18f1: concs in g/L
  - [X] also: apply this to all instances in main text
- [X] 20p1: put gene names in italic
  - [X] also: apply to rest of text
  - [X] also: apply to other chapters
- [X] 24p1: (split with cat 2,3) move earlier in section
- [X] 28p2: add 'may'
- [X] 30p1: add 'My'
- [X] 32p4: add 'we propose'

- [X] 34p2: remove '-'
- [X] 37f1: cite Alan's thesis
- [X] 37p1: add 'the parents'
- [X] 38p3: fluorescent -> fluorescence

* Category 2
Seem to be on to something, but no obvious path forward yet.
Involve harder thought and more work.  Typically involve points of science rather than just wording or argument.  May require new techniques, reading more literature, or thinking about your work in a different way.

** Clarify with Peter
(<2023-08-29>: Clarification now done)
- [X] 02p1: (clarify with Peter) 'synchrony in the chemostat'
  - This argument may have been made in the introduction.  It's the argument about how cells oscillate but don't synchronise.  This argument isn't obvious here, in the numbered list.
- [X] 23f2: (clarify with Peter) 'is there a time scale or number of cycles issue?  are we comparing at similar points?'
  - This is about how O'Neill et al. monitored oscillations for longer or over more periods of oscillations, calling into question about how comparable it is to my study.  Though, he did a potassium ramp.  I can address this by framing it as a caveat of my/his study.
- [X] 38p1: (clarify with Peter) 'might explain the reduction in growth rate' -- does this mean phototoxicity, and where should I discuss this in the text?
  - Yes, and I should mention it in a sentence in the main text (of the biology chapter) when the first HTB2::mCherry growthrate/budding plot appears, as discussion/explanation of what happens.

** Does not involve code
- [X] 01p2: add citations
- [X] 02p2: add citations
- [X] 07f1: clarify if XCF shows delay or advance
- [X] 12p1: re-write/re-interpret slightly re G2/M
  - (Might come back to read this later)
- [X] 14p1: fact-check and add short discussion re mitochondria in CEN.PK
- [X] 24p1: (split with cat 1,3) add 1-2 sentences about sodium being toxic, perhaps with ref/citation
  - also:
- [X] 29p3: clarify how cycles change

** Involves code
- [-] 11f1: discuss/investigate/invent a way to show memory of starvation in flavin signal
  - This likely means showing that the behaviour of the signals after starvation is different from before starvation.  Somehow.  Maybe mutual information.
  - [X] (Cop-out) Short clarification in text.
  - [ ] Mutual information
- [X] 19f2: plot SNRs on the same axes
  - [X] also: kstest2
- [X] 22f1: kstest2
  - [X] also: remove t-test
  - [X] also: glucose-starvation experiment (p.12)

* Category 3
'That idiot didn't get my point at all/didn't bother to read/etc.' (their words, not mine)
Most of the time, these uncover unclear writing: e.g. point not made clearly, buried in uninteresting/confusing text.

** Does not involve code
- [X] 24p1: (split with cat 1,2) make it more obvious that I replaced potassium with sodium
  - Explaining the growth rate spike in this experiment:
    - Intracellular potassium leaks out, leads to cell losing water.  So, volume might drop.  Makes sense if all cells do it at once.
    - However, osmotic response should be faster (1-2 time points) than what is shown...

** Involves code
- [-] 09f1: clarify/discuss mean growth rate & budding plot
  - [X] Make it clear whether I'm showing just the parent or parent + progeny.  Reminder that the 'proper' one is parent + progeny
  - [ ] If have time, try Peter's Gaussian process code.
  - [ ] Julian's preference: progeny (bud) volumes.

(Notes <2023-08-30>)
This will involve:
- Forking and then refactoring ~wela~ to coax it to the CookieCutter directory structure (so that I don't make a mess).
- Fixing the hard-coded g2a_dict attribute so it can be used with the varied key names from different versions of aliby.
- Fixing the wide_df() function so it uses pandas.DataFrame.pivot() properly.
- Silencing output by setting verbose=False in find_gr()
- Waiting a couple of hours for the Gaussian Process to run.  Per experiment.

The software is fairly well-written and well-documented (but the design..?), but I don't have time to debug all this...

Alternative: add together ~postprocessing/dsignal/extraction_general_None_volume~ (parents) and ~postprocessing/dsignal/postprocessing_bud_metric_extraction_general_None_volume~ (progeny), using the indices of ~extraction/Flavin_bgsub/max/mean~ to select cells.  This solves the crux: the 'proper' volume is parent + progeny because while the CDC progresses, some of the increase in volume goes into the bud.


* Notes on tackling the more difficult bits
Go in this order:
- +(No code) Itty-bitty stuff (cat 2)+
- +(No code) Potassium-deficiency stuff+
- +(Code) SNRs and kstest2 stuff+
- (Code) Growth rate stuff
