#+title: Chapter Analysis Feedback

* Notes
- Based on feedback/*_20230907_d4c008fa_DO.pdf
- Categorisation system/War plan taken from [[cite:&heardScientistGuideWriting2016]], along with notes on which category means.
- Notation LXXXX: means line XXXX.  FXX indicates figure 4.XX.

* Category 1
Clear problems with straightforward solutions, e.g. grammar mistakes, reordering of sections, new title

** Text
*** analysis
- [X] L1904: Swap paragraphs L1904-1905 and L1906-1911.
- [X] L1915: Add 'this chapter focuses on'.
- [X] L1938: Join paragraphs.
- [X] L1947: Add 'The software'.
- [X] L1971: Add ref to appendix.
- [X] L1987: 'based' --> 'chosen'.
- [X] L1991: Add 'may'.
- [X] L2015: Say 'I manually labelled'
- [X] L2024: Remove words.
- [X] L2033: 'more positions within' --> 'larger regions of'
- [X] L2041: 'was' --> 'were'
- [X] L2046: 'clusters' --> 'groups'
- [X] L2054-2053: various changes.
- [X] L2063: (I spotted this) italicise zwf1Δ.
- [X] L2080: Reference specific equations to explain how the ranking works.
- [ ] (ADDITIONAL) Make more explicit the ranking in section 2.4.1 in the methods (i.e. use the word 'ranking' somewhere).  Split equations if necessary.
- [X] L2082: Swap sentence beginning L2082 and sentence beginning L2085, and edit language slightly to reflect this.
- [X] L2083: 'pure' --> 'white'
- [X] L2089: make clear this is after visual inspection, probably just add 'after visual inspection'.
- [X] L2091: Add ref to methods.
- [ ] (ADDITIONAL) Make more explicit the false discovery rate in section 2.4.1 in the methods (i.e. use the word 'ranking' somewhere).  Reword as necessary.
- [X] L2112, 2117: Swap fig numbers (should be automatically fixed if F09 is moved).
- [X] L2125-2126: Replace notation (x and z).
- [X] L2127: Add 'computed across all time points'.
- [X] L2136: Define precision & recall, or add to methods so they can be referred to here.
- [X] L2143: Say that it works nicely (in science language).
- [X] L2155: (Probably better in L2153) Add 'details on FN oscillator can be found in section XXX in methods'.
- [X] L2156: Promote section & rename.
- [X] L2184-2195: (Maybe) remove. (OR SHOVE INTO APPENDIX?)
- [X] L2210: Promote section & rename.
- [X] L2213: Refer to methods re FitzHugh-Nagumo oscillator.
- [X] L2223: '4.5.2' --> '4.5.3' (should be automatically updated when sections are promoted)
- [X] L2239, F22: Explain histone 2B.
- [X] L2295: 'support vector classifier' --> 'binary classifier'.
- [X] L2330: Delete 'potentially'.

*** appndx_analysis
- [X] L3008: Rename section.
- [X] L3022: 'estimate' --> ...
- [X] L3024: 'probability' --> 'propensity function'

** Figures
- [X] F01: Add units to window size.
- [X] F03: Add colour legend to figure (use Inkscape and steal elements from fig 4.2)
- [X] F05: Several issues...
  - [X] 4.5a: Add colour legend to figure.
  - [X] Define or delete 'geometric'.
- [X] F09: Move to after fig 4.10
- [X] F12: 'control.' --> 'control' (i.e. remove full stop); strikethrough text --> 'reassigned'.
- [X] F16, 18, 20, 21c, 22c: Remove.
- [X] F24: Move to after L2275.


* Category 2
Seem to be on to something, but no obvious path forward yet.
Involve harder thought and more work.  Typically involve points of science rather than just wording or argument.  May require new techniques, reading more literature, or thinking about your work in a different way.

** Clarify with Diego

** Does not involve code
*** Text
**** analysis
- [X] L1980: Fix dangling sentence.
- [X] L1990: Rephrase sentence to make 'trade-off' clearer.
- [X] L2020: Fact-check statement re UMAP, or delete.
- [X] L2067: Complete paragraph with a sentence that begins with 'however'.
- [X] L2091: Add bit more background (whatever that is).  May need to re-read Glynn et al. (2006).
- [X] L2118: Define accuracy, or replace with precision/recall.  Compare to the 'no-skill' classifier given by class imbalance.
- [X] L2118: (ADDITIONAL) Reference precision & recall definition in the methods.
- [X] L2138: Several issues...
  - [X] Clarify why predicting probability is needed.
  - [X] Explain Platt.
  - [X] Refer to 'predict_proba' in sklearn (resurrect text).
- [ ] L2169: Refer to said diagram to explain what k0 and d0 are.

**** appndx_analysis
- [ ] L2962: Brief intro to UMAP (probably steal from chapt 4 main text), with references.
- [ ] L3018-3020: Correct the maths.

*** Figures
- [ ] F04: Several issues...
  - [ ] Probably worth resurrecting the paragraph that the caption of this figure replaced.
  - [ ] 4.4a: Make clear that it does not show real data, but is just for illustrative purposes.
  - [ ] 4.4b: '10' -> '3'.
  - [ ] 4.4b: Explain pruning in text.  Clarify that this is a kNN graph.
- [ ] F05: (Does not involve code because I already have these figures) Add figures to show what happen if I vary γ; alternatively, make it clear that this method optimises the number of clusters.
- [X] F08: Clarify whether this is real 'training' as in ML, or what it is otherwise.
- [X] F10: Add text in-between (whatever that is).

** Involves code
- [ ] F14: Add diagram to explain what k0 and d0 are.
- [ ] L2063: Add fig to show that some zwf1Δ time series resembled BY4741 time series.

* Category 3
'That idiot didn't get my point at all/didn't bother to read/etc.' (their words, not mine)
Most of the time, these uncover unclear writing: e.g. point not made clearly, buried in uninteresting/confusing text.

** Does not involve code
- [X] L2076: 'section 2.4.1' --> refer to methods 2.4.1, or something along those lines.  Also do this with other similar occurrences in the text (all than begin with 'section 2*').

** Involves code

* Notes on tackling the more difficult bits
