#+title: Chapter Analysis 20230829 Restructure

From: <2023-08-29 Tue> meeting with Diego

- 2. Methods (~ch:methods~)
  - 2.1. Strains
  - 2.2. Single-cell microfluidics
  - 2.3. Segmentation, extraction, post-processing
  - 2.4. (NEW) Computational methods
    - 2.4.1. Classical periodogram (from ~subsec:analysis-classification-spectral~)
    - 2.4.2. AR model (from ~subsec:analysis-classification-ar~)
    - 2.4.3. ACF (from ~subsec:analysis-characterisation-acf-maths~)
    - 2.4.4. Signal-to-noise ratio (from ~subsec:analysis-characterisation-noise~)

- 3. Microfluidics and fluorescence... (~ch:biology~)
  - This chapter should be moved here because it's a School of Biological Sciences PhD -- biological results first.

- 4. Analysis of oscillatory... (~ch:analysis~)
  - Intro
    - The main point/motivation should be: I wanted to find whether time series were oscillatory or not.  Turns out it was more difficult than I had thought, and the results are inconclusive (this is okay for a thesis).
  - 4.1. Analysing time series...
  - 4.2. "Data cleaning" (~sec:analysis-cleaning~)
  - 4.3. Clustering (~sec:analysis-clustering~)
    - Important to have this section and early in the chapter because the first question someone would ask is, 'what does the dataset look like'.  In a sense, this relates to data exploration.  It is okay to show that they don't work very well.
    - 4.3.1. UMAP (~subsec:analysis-clustering-umap~)
    - 4.3.2. Graph-based clustering (~subsec:analysis-clustering-graphclustering~)
  - 4.4. "Detection of rhythmicity" (~sec:analysis-classification~)
    - Should have more specific section names.
    - The make-up of this section and the names are good.
    - Move most of the maths to methods because it gets in the way.  Expand the 'rump' subsections slightly.  The three subsections should then be of roughly the same length.
    - 4.4.1. Spectral methods (~subsec:analysis-classification-spectral~)
      - MOVE TO METHODS: Equations to compute the classical periodogram.
    - 4.4.2. Model fitting (~subsec:analysis-classification-ar~)
      - MOVE TO METHODS: Equations to compute AR model.
    - 4.4.3. Machine learning (~subsec:analysis-classification-ml~)
  - 4.5. "Period estimation" (~sec:analysis-characterisation~)
    - Promote the ACF stuff (subsubsections --> sections)
    - 4.5.1. Synthetic oscillations
      - Must be clear that these are synthetic oscillations and the purpose is to tune the methods.  The distinction is important because up till now, I've looked at real data.
      - MOVE TO METHODS: Mathematical definitions (all of it, including the FitzHugh-Nagumo definitions)
      - INCLUDE: ~subsubsec:analysis-characterisation-acf-sinusoid~, ~subsubsec:analysis-characterisation-acf-fhn~
    - 4.5.2. Real data (~fig:acf-sinusoid-biol~, ~fig:acf-fhn-biol~)
    - MOVE TO DISCUSSION SECTION: Combining methods...
      - NIX: ~fig:acf-fft-example~
    - MOVE TO METHODS: Noise
  - 4.6. "Detection of synchrony" (~sec:analysis-correlation~)
    - 4.6.1. Synthetic data (sinusoids and FitzHugh-Nagumo)
    - 4.6.2. Real data (resurrect the big commented-out chunk)
  - 4.7. Discussion
    - INCLUDE: ~subsec:analysis-characterisation-combined~


Bits of text that will change after this re-structure:
- Intro: List of chapters, i.e. swap 3 and 4
- Analysis/Intro: Clarify motivation, swap items in list and rename them


General comments
- Don't worry too much about the length of the thesis.  More important to have chapters that are roughly the same lengths.
