#+title: Chapter Analysis Feedback

* Notes
- Based on feedback/*_20230907_d4c008fa_DO.pdf
- Categorisation system/War plan taken from [[cite:&heardScientistGuideWriting2016]], along with notes on which category means.
- Notation LXXXX: means line XXXX.  FXX indicates figure 4.XX.

* Category 1
Clear problems with straightforward solutions, e.g. grammar mistakes, reordering of sections, new title


* Category 2
Seem to be on to something, but no obvious path forward yet.
Involve harder thought and more work.  Typically involve points of science rather than just wording or argument.  May require new techniques, reading more literature, or thinking about your work in a different way.

** Clarify with Diego

** Does not involve code

** Involves code

* Category 3
'That idiot didn't get my point at all/didn't bother to read/etc.' (their words, not mine)
Most of the time, these uncover unclear writing: e.g. point not made clearly, buried in uninteresting/confusing text.

** Does not involve code

** Involves code

* Notes on tackling the more difficult bits
